FROM cypress/included:13.17.0

WORKDIR /e2e

COPY package.json .

# Copy Cypress tests and config
COPY ./cypress ./cypress
COPY ./cypress.config.js .

RUN npm install

CMD ["npx", "cypress", "run", "--reporter", "junit", "--reporter-options", "mochaFile=/e2e/results/test-results.xml"]
